// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/nigelgott/terra/protobufs/heightmap.proto

package com.nigelgott.terra.protobufs;

public final class Heightmap {
  private Heightmap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeightMapMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeightMapMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 x = 1;</code>
     */
    int getX();

    /**
     * <code>optional int32 y = 2;</code>
     */
    int getY();

    /**
     * <code>repeated int32 height = 3;</code>
     */
    java.util.List<java.lang.Integer> getHeightList();
    /**
     * <code>repeated int32 height = 3;</code>
     */
    int getHeightCount();
    /**
     * <code>repeated int32 height = 3;</code>
     */
    int getHeight(int index);
  }
  /**
   * Protobuf type {@code HeightMapMessage}
   */
  public  static final class HeightMapMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HeightMapMessage)
      HeightMapMessageOrBuilder {
    // Use HeightMapMessage.newBuilder() to construct.
    private HeightMapMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeightMapMessage() {
      x_ = 0;
      y_ = 0;
      height_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HeightMapMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              x_ = input.readInt32();
              break;
            }
            case 16: {

              y_ = input.readInt32();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                height_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              height_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                height_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                height_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          height_ = java.util.Collections.unmodifiableList(height_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nigelgott.terra.protobufs.Heightmap.internal_static_HeightMapMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nigelgott.terra.protobufs.Heightmap.internal_static_HeightMapMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage.class, com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage.Builder.class);
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>optional int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>optional int32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> height_;
    /**
     * <code>repeated int32 height = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getHeightList() {
      return height_;
    }
    /**
     * <code>repeated int32 height = 3;</code>
     */
    public int getHeightCount() {
      return height_.size();
    }
    /**
     * <code>repeated int32 height = 3;</code>
     */
    public int getHeight(int index) {
      return height_.get(index);
    }
    private int heightMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (x_ != 0) {
        output.writeInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeInt32(2, y_);
      }
      if (getHeightList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(heightMemoizedSerializedSize);
      }
      for (int i = 0; i < height_.size(); i++) {
        output.writeInt32NoTag(height_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < height_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(height_.get(i));
        }
        size += dataSize;
        if (!getHeightList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        heightMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage)) {
        return super.equals(obj);
      }
      com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage other = (com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage) obj;

      boolean result = true;
      result = result && (getX()
          == other.getX());
      result = result && (getY()
          == other.getY());
      result = result && getHeightList()
          .equals(other.getHeightList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      if (getHeightCount() > 0) {
        hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getHeightList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeightMapMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeightMapMessage)
        com.nigelgott.terra.protobufs.Heightmap.HeightMapMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nigelgott.terra.protobufs.Heightmap.internal_static_HeightMapMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nigelgott.terra.protobufs.Heightmap.internal_static_HeightMapMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage.class, com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage.Builder.class);
      }

      // Construct using com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0;

        y_ = 0;

        height_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nigelgott.terra.protobufs.Heightmap.internal_static_HeightMapMessage_descriptor;
      }

      public com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage getDefaultInstanceForType() {
        return com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage.getDefaultInstance();
      }

      public com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage build() {
        com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage buildPartial() {
        com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage result = new com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.x_ = x_;
        result.y_ = y_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          height_ = java.util.Collections.unmodifiableList(height_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.height_ = height_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage) {
          return mergeFrom((com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage other) {
        if (other == com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        if (!other.height_.isEmpty()) {
          if (height_.isEmpty()) {
            height_ = other.height_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureHeightIsMutable();
            height_.addAll(other.height_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int x_ ;
      /**
       * <code>optional int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>optional int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> height_ = java.util.Collections.emptyList();
      private void ensureHeightIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          height_ = new java.util.ArrayList<java.lang.Integer>(height_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 height = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getHeightList() {
        return java.util.Collections.unmodifiableList(height_);
      }
      /**
       * <code>repeated int32 height = 3;</code>
       */
      public int getHeightCount() {
        return height_.size();
      }
      /**
       * <code>repeated int32 height = 3;</code>
       */
      public int getHeight(int index) {
        return height_.get(index);
      }
      /**
       * <code>repeated int32 height = 3;</code>
       */
      public Builder setHeight(
          int index, int value) {
        ensureHeightIsMutable();
        height_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 height = 3;</code>
       */
      public Builder addHeight(int value) {
        ensureHeightIsMutable();
        height_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 height = 3;</code>
       */
      public Builder addAllHeight(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureHeightIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, height_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 height = 3;</code>
       */
      public Builder clearHeight() {
        height_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:HeightMapMessage)
    }

    // @@protoc_insertion_point(class_scope:HeightMapMessage)
    private static final com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage();
    }

    public static com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HeightMapMessage>
        PARSER = new com.google.protobuf.AbstractParser<HeightMapMessage>() {
      public HeightMapMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HeightMapMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HeightMapMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeightMapMessage> getParserForType() {
      return PARSER;
    }

    public com.nigelgott.terra.protobufs.Heightmap.HeightMapMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeightMapMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeightMapMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-com/nigelgott/terra/protobufs/heightma" +
      "p.proto\"8\n\020HeightMapMessage\022\t\n\001x\030\001 \001(\005\022\t" +
      "\n\001y\030\002 \001(\005\022\016\n\006height\030\003 \003(\005B;\n\035com.nigelgo" +
      "tt.terra.protobufs\252\002\031NigelGott.Terra.Pro" +
      "tobufsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HeightMapMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeightMapMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeightMapMessage_descriptor,
        new java.lang.String[] { "X", "Y", "Height", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
