// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/nigelgott/terra/protobufs/heightmap.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NigelGott.Terra.Protobufs {

  /// <summary>Holder for reflection information generated from com/nigelgott/terra/protobufs/heightmap.proto</summary>
  public static partial class HeightmapReflection {

    #region Descriptor
    /// <summary>File descriptor for com/nigelgott/terra/protobufs/heightmap.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HeightmapReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1jb20vbmlnZWxnb3R0L3RlcnJhL3Byb3RvYnVmcy9oZWlnaHRtYXAucHJv",
            "dG8iOAoQSGVpZ2h0TWFwTWVzc2FnZRIJCgF4GAEgASgFEgkKAXkYAiABKAUS",
            "DgoGaGVpZ2h0GAMgAygFQjsKHWNvbS5uaWdlbGdvdHQudGVycmEucHJvdG9i",
            "dWZzqgIZTmlnZWxHb3R0LlRlcnJhLlByb3RvYnVmc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NigelGott.Terra.Protobufs.HeightMapMessage), global::NigelGott.Terra.Protobufs.HeightMapMessage.Parser, new[]{ "X", "Y", "Height" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class HeightMapMessage : pb::IMessage<HeightMapMessage> {
    private static readonly pb::MessageParser<HeightMapMessage> _parser = new pb::MessageParser<HeightMapMessage>(() => new HeightMapMessage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HeightMapMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NigelGott.Terra.Protobufs.HeightmapReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeightMapMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeightMapMessage(HeightMapMessage other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      height_ = other.height_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HeightMapMessage Clone() {
      return new HeightMapMessage(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private int x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private int y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_height_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> height_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Height {
      get { return height_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HeightMapMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HeightMapMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (X != other.X) return false;
      if (Y != other.Y) return false;
      if(!height_.Equals(other.height_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0) hash ^= X.GetHashCode();
      if (Y != 0) hash ^= Y.GetHashCode();
      hash ^= height_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (X != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(X);
      }
      if (Y != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Y);
      }
      height_.WriteTo(output, _repeated_height_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (X != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(X);
      }
      if (Y != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Y);
      }
      size += height_.CalculateSize(_repeated_height_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HeightMapMessage other) {
      if (other == null) {
        return;
      }
      if (other.X != 0) {
        X = other.X;
      }
      if (other.Y != 0) {
        Y = other.Y;
      }
      height_.Add(other.height_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            X = input.ReadInt32();
            break;
          }
          case 16: {
            Y = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            height_.AddEntriesFrom(input, _repeated_height_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
