// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/nigelgott/terra/protobufs/response.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NigelGott.Terra.Protobufs {

  /// <summary>Holder for reflection information generated from com/nigelgott/terra/protobufs/response.proto</summary>
  public static partial class ResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for com/nigelgott/terra/protobufs/response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cixjb20vbmlnZWxnb3R0L3RlcnJhL3Byb3RvYnVmcy9yZXNwb25zZS5wcm90",
            "byJzCg9SZXNwb25zZU1lc3NhZ2USKwoEdHlwZRgBIAEoDjIdLlJlc3BvbnNl",
            "TWVzc2FnZS5SZXNwb25zZVR5cGUSFgoObnVtT2ZSZXNwb25zZXMYAiABKAUi",
            "GwoMUmVzcG9uc2VUeXBlEgsKB1RFUlJBSU4QAEI7Ch1jb20ubmlnZWxnb3R0",
            "LnRlcnJhLnByb3RvYnVmc6oCGU5pZ2VsR290dC5UZXJyYS5Qcm90b2J1ZnNi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NigelGott.Terra.Protobufs.ResponseMessage), global::NigelGott.Terra.Protobufs.ResponseMessage.Parser, new[]{ "Type", "NumOfResponses" }, null, new[]{ typeof(global::NigelGott.Terra.Protobufs.ResponseMessage.Types.ResponseType) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ResponseMessage : pb::IMessage<ResponseMessage> {
    private static readonly pb::MessageParser<ResponseMessage> _parser = new pb::MessageParser<ResponseMessage>(() => new ResponseMessage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResponseMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NigelGott.Terra.Protobufs.ResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseMessage(ResponseMessage other) : this() {
      type_ = other.type_;
      numOfResponses_ = other.numOfResponses_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseMessage Clone() {
      return new ResponseMessage(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::NigelGott.Terra.Protobufs.ResponseMessage.Types.ResponseType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NigelGott.Terra.Protobufs.ResponseMessage.Types.ResponseType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "numOfResponses" field.</summary>
    public const int NumOfResponsesFieldNumber = 2;
    private int numOfResponses_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NumOfResponses {
      get { return numOfResponses_; }
      set {
        numOfResponses_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResponseMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResponseMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (NumOfResponses != other.NumOfResponses) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (NumOfResponses != 0) hash ^= NumOfResponses.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (NumOfResponses != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NumOfResponses);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (NumOfResponses != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumOfResponses);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResponseMessage other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.NumOfResponses != 0) {
        NumOfResponses = other.NumOfResponses;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            type_ = (global::NigelGott.Terra.Protobufs.ResponseMessage.Types.ResponseType) input.ReadEnum();
            break;
          }
          case 16: {
            NumOfResponses = input.ReadInt32();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ResponseMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum ResponseType {
        [pbr::OriginalName("TERRAIN")] Terrain = 0,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
