// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/nigelgott/terra/protobufs/response.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NigelGott.Terra.Protobufs {

  /// <summary>Holder for reflection information generated from com/nigelgott/terra/protobufs/response.proto</summary>
  public static partial class ResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for com/nigelgott/terra/protobufs/response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cixjb20vbmlnZWxnb3R0L3RlcnJhL3Byb3RvYnVmcy9yZXNwb25zZS5wcm90",
            "bxorY29tL25pZ2VsZ290dC90ZXJyYS9wcm90b2J1ZnMvcmVxdWVzdC5wcm90",
            "byJfCg9SZXNwb25zZU1lc3NhZ2USKwoEdHlwZRgBIAEoDjIdLlJlc3BvbnNl",
            "TWVzc2FnZS5SZXNwb25zZVR5cGUiHwoMUmVzcG9uc2VUeXBlEg8KC1dPUkxE",
            "X1NUQVRFEAAiRAoKV29ybGRTdGF0ZRIRCgl3b3JsZFNpemUYASABKAUSIwoO",
            "cGxheWVyTG9jYXRpb24YAiABKAsyCy5GbG9hdENvb3JkQjsKHWNvbS5uaWdl",
            "bGdvdHQudGVycmEucHJvdG9idWZzqgIZTmlnZWxHb3R0LlRlcnJhLlByb3Rv",
            "YnVmc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::NigelGott.Terra.Protobufs.RequestReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NigelGott.Terra.Protobufs.ResponseMessage), global::NigelGott.Terra.Protobufs.ResponseMessage.Parser, new[]{ "Type" }, null, new[]{ typeof(global::NigelGott.Terra.Protobufs.ResponseMessage.Types.ResponseType) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NigelGott.Terra.Protobufs.WorldState), global::NigelGott.Terra.Protobufs.WorldState.Parser, new[]{ "WorldSize", "PlayerLocation" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ResponseMessage : pb::IMessage<ResponseMessage> {
    private static readonly pb::MessageParser<ResponseMessage> _parser = new pb::MessageParser<ResponseMessage>(() => new ResponseMessage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResponseMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NigelGott.Terra.Protobufs.ResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseMessage(ResponseMessage other) : this() {
      type_ = other.type_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseMessage Clone() {
      return new ResponseMessage(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::NigelGott.Terra.Protobufs.ResponseMessage.Types.ResponseType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NigelGott.Terra.Protobufs.ResponseMessage.Types.ResponseType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResponseMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResponseMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResponseMessage other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            type_ = (global::NigelGott.Terra.Protobufs.ResponseMessage.Types.ResponseType) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ResponseMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum ResponseType {
        [pbr::OriginalName("WORLD_STATE")] WorldState = 0,
      }

    }
    #endregion

  }

  public sealed partial class WorldState : pb::IMessage<WorldState> {
    private static readonly pb::MessageParser<WorldState> _parser = new pb::MessageParser<WorldState>(() => new WorldState());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WorldState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NigelGott.Terra.Protobufs.ResponseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WorldState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WorldState(WorldState other) : this() {
      worldSize_ = other.worldSize_;
      PlayerLocation = other.playerLocation_ != null ? other.PlayerLocation.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WorldState Clone() {
      return new WorldState(this);
    }

    /// <summary>Field number for the "worldSize" field.</summary>
    public const int WorldSizeFieldNumber = 1;
    private int worldSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int WorldSize {
      get { return worldSize_; }
      set {
        worldSize_ = value;
      }
    }

    /// <summary>Field number for the "playerLocation" field.</summary>
    public const int PlayerLocationFieldNumber = 2;
    private global::NigelGott.Terra.Protobufs.FloatCoord playerLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::NigelGott.Terra.Protobufs.FloatCoord PlayerLocation {
      get { return playerLocation_; }
      set {
        playerLocation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WorldState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WorldState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WorldSize != other.WorldSize) return false;
      if (!object.Equals(PlayerLocation, other.PlayerLocation)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (WorldSize != 0) hash ^= WorldSize.GetHashCode();
      if (playerLocation_ != null) hash ^= PlayerLocation.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (WorldSize != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(WorldSize);
      }
      if (playerLocation_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PlayerLocation);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (WorldSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WorldSize);
      }
      if (playerLocation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerLocation);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WorldState other) {
      if (other == null) {
        return;
      }
      if (other.WorldSize != 0) {
        WorldSize = other.WorldSize;
      }
      if (other.playerLocation_ != null) {
        if (playerLocation_ == null) {
          playerLocation_ = new global::NigelGott.Terra.Protobufs.FloatCoord();
        }
        PlayerLocation.MergeFrom(other.PlayerLocation);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            WorldSize = input.ReadInt32();
            break;
          }
          case 18: {
            if (playerLocation_ == null) {
              playerLocation_ = new global::NigelGott.Terra.Protobufs.FloatCoord();
            }
            input.ReadMessage(playerLocation_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
